/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 15/04/2010, 06:54:02 PM
 */

package p05e01;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PanelPrincipal extends javax.swing.JPanel {

   private ArregloProductos ap;
    public PanelPrincipal() {
        initComponents();
        ap= new ArregloProductos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Entrada"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        jPanel1.add(txtCodigo);

        txtDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));
        jPanel1.add(txtDescripcion);

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));
        jPanel1.add(txtPrecio);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusca);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnListado.setText("Lista");
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnListado);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        txtSalida.setBorder(javax.swing.BorderFactory.createTitledBorder("Salida"));
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       int p=ap.busca(leeCodigo());
       if(p!=-1)
           mensaje("Error:Codigo Repetido");
       else{
           Producto nuevo=new Producto(leeCodigo(),leeDescripcion(),leePrecio());
           lista(nuevo);
           ap.agrega(nuevo);
       }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
listado();
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
       int p=ap.busca(leeCodigo());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           Producto pp=ap.getProducto(p);
           lista(pp);
       }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        int p=ap.busca(leeCodigo());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           ap.elimina(p);
           mensaje("Eliminacion satisfactoria");
       }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        imprime("Precio promedio\t:" +ap.PrecioPromedio());
        imprime("Precio mas alto\t:" +ap.MayorPrecio());
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        
         int p=ap.busca(leeCodigo());
       if(p==-1)
           mensaje("Error: Codigo No encontrado");
       else{
           
           Producto nuevo=new Producto(leeCodigo(),leeDescripcion(),leePrecio());
         
           ap.reemplaza(nuevo, p);
          
       }
        
        
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    txtCodigo.setText("");
    txtDescripcion.setText("");
    txtPrecio.setText("");
    txtSalida.setText("");
       
    }//GEN-LAST:event_btnBorrarActionPerformed

    public void listado(){
    txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
    for(int i=0;i<ap.getN();i++){
        Producto p=ap.getProducto(i);
        imprime(p.getCodigo()+"\t"+p.getDescripcion()+"\t"+p.getPrecio());
    }
}

    public String leeCodigo(){
    return txtCodigo.getText();
}
public String leeDescripcion(){
    return txtDescripcion.getText();
}
public double leePrecio(){
    return Double.parseDouble(txtPrecio.getText());
}
public void mensaje(String s){
    JOptionPane.showMessageDialog(this, s);//ctrl+barra espaciadora pa q busque JOptionPane
}
public void lista(Producto p){
    imprime("Codigo\t: "+p.getCodigo());
    imprime("Descripcion\t: "+p.getDescripcion());
    imprime("Precio\t: "+p.getPrecio());
}
public void imprime(String s){
    txtSalida.append(s+"\n");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables

}
