/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p06e01;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    ArregloProductos ap;   
    public PanelPrincipal() {
        initComponents();
        ap = new ArregloProductos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnRporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cboOpcion = new javax.swing.JComboBox();
        txtCuanto = new javax.swing.JTextField();
        txtMayorA = new javax.swing.JTextField();
        txtMenorA = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1);
        jPanel1.add(txtCodigo);

        jLabel2.setText("Descripcion");
        jPanel1.add(jLabel2);
        jPanel1.add(txtDescripcion);

        jLabel3.setText("Precio");
        jPanel1.add(jLabel3);
        jPanel1.add(txtPrecio);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusca);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnRporte.setText("Reporte");
        btnRporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnRporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        btnOpciones.setText("Aumentar o disminuir");
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnOpciones);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Aumentar 15%");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setText("Productos < al promedio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        cboOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "Aumentar", "Disminuir" }));
        jPanel6.add(cboOpcion);

        txtCuanto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuanto..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel6.add(txtCuanto);

        txtMayorA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mayores a ...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        txtMayorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMayorAActionPerformed(evt);
            }
        });
        jPanel6.add(txtMayorA);

        txtMenorA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menores a...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        txtMenorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenorAActionPerformed(evt);
            }
        });
        jPanel6.add(txtMenorA);

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Palabra de ayuda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel7.add(txtBuscar);

        jButton3.setText("Busqueda avansada");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       txtCodigo.setText("");
       txtDescripcion.setText("");
       txtPrecio.setText("");
       txtSalida.setText("");
       txtCodigo.requestFocus();            
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       int p=ap.busca(leeCodigo());
       if(p!=-1){
        mensaje("Error: Codigo Repetido");
       }else{ 
        Producto nuevo=new Producto(leeCodigo(),leeDescripcion(),leePrecio());
       ap.agrega(nuevo);
      
    }//GEN-LAST:event_btnNuevoActionPerformed
    }
    
    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        int p=ap.busca(leeCodigo()); 
        if(p!=-1){
        mensaje("Error: Codigo no encontrado");
       }else{ 
        Producto pp=ap.getProducto(p);
       lista(pp);
    }       
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
      int p=ap.busca(leeCodigo());
      if(p!=-1){
        mensaje("Error: Codigo no encontrado");
       }else{ 
        Producto nuevo=new Producto(leeCodigo(),leeDescripcion(),leePrecio());
       ap.actualiza(nuevo, p);
    }       
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
      int p=ap.busca(leeCodigo()); 
      if(p!=-1){
        mensaje("Error: Codigo no encontrado");
       }else{ 
        ap.elimina(p);
       mensaje("Eliminado Satisfactoriamente");
    }       
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
    listado(); 
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnRporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRporteActionPerformed
     imprime("Precio más alto\t:"+ap.mayorPrecio());
     imprime("Precio promedio\t:"+ap.precioPromedio());
     imprime("Precio más bajo\t:"+ap.menorPrecio());
    }//GEN-LAST:event_btnRporteActionPerformed

    private void txtMenorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenorAActionPerformed

    private void txtMayorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMayorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMayorAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
      for(int i=0;i<ap.getN();i++){
          Producto p=ap.getProducto(i);
          imprime(p.getCodigo()+"\t"+p.getDescripcion()+"\t"+ap.Aumentar15(p));
      }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
txtSalida.setText("");
        txtSalida.setText("");
        imprime("los productos menores al promedio es:"+ap.Menores());
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
     txtSalida.setText("");
      if(leeBusca()==1){
       txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
      for(int i=0;i<ap.getN();i++){
          Producto p=ap.getProducto(i);
          imprime(p.getCodigo()+"\t"+p.getDescripcion()+"\t"+ap.aumentarValor(p, leeMenor(), leeMayor(), leeCuanto()));
      }
      }  
      
      if(leeBusca()==2){
       txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
      for(int i=0;i<ap.getN();i++){
          Producto p=ap.getProducto(i);
          imprime(p.getCodigo()+"\t"+p.getDescripcion()+"\t"+ap.disminuirValor(p,leeMenor() , leeMayor(), leeCuanto()));
      }
      } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     txtSalida.setText("");
        txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
      for(int i=0;i<ap.getN();i++){
          Producto p=ap.getProducto(i);
          if(ap.busquedaPre(p,leeBusque()) != 0){
          imprime(ap.busquedaCod(p,leeBusque())+"\t"+ap.busquedaDes(p,leeBusque())+"\t"+ap.busquedaPre(p,leeBusque()));
      }}
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

     
    
    
    private int leeBusca(){return cboOpcion.getSelectedIndex();}
    private int leeMayor(){return Integer.parseInt(txtMayorA.getText());}
    
    private int leeMenor(){return Integer.parseInt(txtMenorA.getText());}
    
    private int leeCuanto(){return Integer.parseInt(txtCuanto.getText());}
    
    private String  leeBusque(){return txtBuscar.getText();}
    
    private String leeCodigo(){
        return txtCodigo.getText(); 
    }
    private String leeDescripcion(){
        return txtDescripcion.getText();
    }
    private double leePrecio(){
        return Double.parseDouble(txtPrecio.getText());
    }
    
    public void lista(Producto p){
        imprime("Codigo\t:"+p.getCodigo());
        imprime("Descripcion\t:"+p.getDescripcion());
        imprime("Precio\t:"+p.getPrecio());
    }
    
    public void imprime(String s){
        txtSalida.append(s+"\n");
    }
public void listado(){
        txtSalida.setText("Codigo\tDescripcion\tPrecio\n");
      for(int i=0;i<ap.getN();i++){
          Producto p=ap.getProducto(i);
          imprime(p.getCodigo()+"\t"+p.getDescripcion()+"\t"+p.getPrecio());
      }
    }

public void mensaje(String s){
    JOptionPane.showMessageDialog(this, s);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnRporte;
    private javax.swing.JComboBox cboOpcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCuanto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtMayorA;
    private javax.swing.JTextField txtMenorA;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
