/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 18-feb-2013, 13:42:12
 */
package p05e02;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /** Creates new form PanelPrincipal */
       private ArregloPersonas ap;

     public PanelPrincipal() {
        initComponents();
      ap= new ArregloPersonas();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("D.N.I");
        jPanel1.add(jLabel5);
        jPanel1.add(txtDni);

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);
        jPanel1.add(txtNombre);

        jLabel2.setText("Apellido:");
        jPanel1.add(jLabel2);
        jPanel1.add(txtApellido);

        jLabel3.setText("Edad:");
        jPanel1.add(jLabel3);

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdad);

        jLabel4.setText("Peso:");
        jPanel1.add(jLabel4);
        jPanel1.add(txtPeso);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusca);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtEdadActionPerformed

private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
// TODO add your handling code here:
    txtDni.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtEdad.setText("");
    txtPeso.setText("");
    txtSalida.setText("");
      
    
    
}//GEN-LAST:event_btnBorrarActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
    int p=ap.busca(leeDni());
       if(p!=-1)
           mensaje("Error: DNI Repetido");
       else{
           Persona nuevo=new Persona(leeDni(),leeNombre(),leeApellido(),leeEdad(), leePeso());
           lista(nuevo);
           ap.agrega(nuevo);
       }
    //codigo anterior 
    /*
    Persona nuevo=new Persona(leeDni(),leeNombre(),leeApellido(),leeEdad(),leePeso());
     
    lista(nuevo);
      */ 
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
// TODO add your handling code here:
    int p=ap.busca(leeDni());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           Persona pp=ap.getPersona(p);
           lista(pp);
       }
    
    
}//GEN-LAST:event_btnBuscaActionPerformed

private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
// TODO add your handling code here:
    
    int p=ap.busca(leeDni());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           ap.elimina(p);
           mensaje("Eliminacion satisfactoria");
       }
    
    
}//GEN-LAST:event_btnEliminaActionPerformed

private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
// TODO add your handling code here:
    
     imprime("Precio promedio\t:" +ap.PesoPromedio());
     imprime("Precio mas alto\t:" +ap.MayorPeso());
    
    
}//GEN-LAST:event_btnReporteActionPerformed

private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
// TODO add your handling code here:
    listado();
}//GEN-LAST:event_btnListaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        
        int p=ap.busca(leeDni());
       if(p==-1)
           mensaje("Error: DNI No encontrado");
       else{
           mensaje("Ingrese nuevo valores");
           Persona nuevo=new Persona(leeDni(),leeNombre(),leeApellido(),leeEdad(), leePeso());

           
           ap.reemplaza(nuevo, p);
           
           
       }
        
    }//GEN-LAST:event_btnModificaActionPerformed


private String leeNombre(){return txtNombre.getText();}
private String leeApellido(){return txtApellido.getText();}
private int leeEdad(){return Integer.parseInt(txtEdad.getText());}
private double leePeso(){return Double.parseDouble(txtPeso.getText());}
private String leeDni(){return txtDni.getText();}


public void listado(){
    txtSalida.setText("DNI\tNombre\tApellido\tEdad\tPeso\n");
    for(int i=0;i<ap.getN();i++){
        Persona p=ap.getPersona(i);
        imprime(p.getDni()+"\t"+p.getNombre()+"\t"+p.getApellido()+"\t"+p.getEdad()+"\t"+p.getPeso());
    }
}

private void lista(Persona p)
{   imprime("Dni:\t"+p.getDni());
    imprime("Nombre:\t"+p.getNombre());
    imprime("Apellido:\t"+p.getApellido());
    imprime("Edad:\t"+p.getEdad());
    imprime("Peso:\t"+p.getPeso());
}

private void imprime(String s)
{  txtSalida.append(s+"\n"); }

public void mensaje(String s){
    JOptionPane.showMessageDialog(this, s);//ctrl+barra espaciadora pa q busque JOptionPane
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
