
package p05e04;
import javax.swing.JOptionPane;

public class PanelPrincipal extends javax.swing.JPanel {
   private ArregloDNI ap;

    /** Creates new form PanelPrincipal */
    public PanelPrincipal() {
        initComponents();
        
        ap= new ArregloDNI();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtDiaEmision = new javax.swing.JTextField();
        cboMesEmision = new javax.swing.JComboBox();
        txtAñoEmision = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtDiaCaducidad = new javax.swing.JTextField();
        cboMesCaducidad = new javax.swing.JComboBox();
        txtAñoCaducidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de DNI"));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jPanel2.add(txtNombres);

        txtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        jPanel2.add(txtApellidos);

        txtEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        jPanel2.add(txtEdad);

        txtPeso.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        jPanel2.add(txtPeso);

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Emision"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        txtDiaEmision.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia"));
        jPanel5.add(txtDiaEmision);

        cboMesEmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        cboMesEmision.setBorder(null);
        jPanel5.add(cboMesEmision);

        txtAñoEmision.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));
        jPanel5.add(txtAñoEmision);

        jPanel4.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Caducidad"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        txtDiaCaducidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia"));
        jPanel6.add(txtDiaCaducidad);

        cboMesCaducidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cboMesCaducidad.setBorder(null);
        jPanel6.add(cboMesCaducidad);

        txtAñoCaducidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));
        jPanel6.add(txtAñoCaducidad);

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel7.add(btnNuevo);

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel7.add(btnBusca);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel7.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel7.add(btnElimina);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel7.add(btnLista);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel7.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel7.add(btnBorrar);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNumeroActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
   
    int p=ap.busca(leeNumero());
       if(p!=-1)
           mensaje("Error:DNI Repetido");
       else{
 
           DNI nuevo = new DNI(leeNumero(),
             new Persona(leeNombres(), leeApellidos(), leeEdad(), leePeso()),
             new Fecha(leeDiaEmision(), leeMesEmision(), leeAñoEmision()), 
             new Fecha(leeDiaCaducidad(), leeMesCaducidad(), leeAñoCaducidad()) );
           
           
           lista(nuevo);
           ap.agrega(nuevo);
       }
         
}//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
         int p=ap.busca(leeNumero());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           DNI pp=ap.getDNI(p);
           lista(pp);
       }
        
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
          int p=ap.busca(leeNumero());
       if(p==-1)
           mensaje("Error: DNI No encontrado");
       else{
           
          DNI nuevo = new DNI(leeNumero(),
             new Persona(leeNombres(), leeApellidos(), leeEdad(), leePeso()),
             new Fecha(leeDiaEmision(), leeMesEmision(), leeAñoEmision()), 
             new Fecha(leeDiaCaducidad(), leeMesCaducidad(), leeAñoCaducidad()) );
         
           ap.reemplaza(nuevo, p);
          
       }
        
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        // TODO add your handling code here:
        
         int p=ap.busca(leeNumero());
       if(p==-1)
           mensaje("Error: DNI no existe");
       else{
           ap.elimina(p);
           mensaje("Eliminacion satisfactoria");
       }
        
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        
        listado();
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        
         imprime("Precio promedio\t:" +ap.PesoPromedio());
        imprime("Precio mas alto\t:" +ap.MayorPeso());
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    txtNumero.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtEdad.setText("");    
    txtPeso.setText("");
    txtDiaEmision.setText("");
    txtAñoEmision.setText("");
    txtDiaCaducidad.setText(""); 
    txtAñoCaducidad.setText("");
    cboMesEmision.setSelectedIndex(0);
    cboMesCaducidad.setSelectedIndex(0);   
        
    }//GEN-LAST:event_btnBorrarActionPerformed

private String leeNumero(){return txtNumero.getText();}
//guarda variables en la clase PERSONA
private String leeNombres(){return txtNombres.getText();}
private String leeApellidos(){return txtApellidos.getText();}
private int leeEdad(){return Integer.parseInt(txtEdad.getText());}
private double leePeso(){return Double.parseDouble(txtPeso.getText());}
private int leeDiaEmision(){ return Integer.parseInt(txtDiaEmision.getText());} 
private int leeMesEmision(){ return cboMesEmision.getSelectedIndex();} 
private int leeAñoEmision(){ return Integer.parseInt(txtAñoEmision.getText());} 
private int leeDiaCaducidad(){ return Integer.parseInt(txtDiaCaducidad.getText());}
//guarda variables en la clase FECHA

private int leeMesCaducidad(){ return cboMesCaducidad.getSelectedIndex();} 
private int leeAñoCaducidad(){ return Integer.parseInt(txtAñoCaducidad.getText());} 

    public void listado(){
    txtSalida.setText("Numoro\tNombre\tApellido\tEdad\tPeso\tFecha Emision\tFecha Caducidad\n");
    for(int i=0;i<ap.getN();i++){
        DNI p=ap.getDNI(i);
        imprime(p.getNumero()+"\t"+p.getDueño().getNombre()+"\t"+p.getDueño().getApellido()+"\t"+ p.getDueño().getEdad()+"\t"+p.getDueño().getPeso()+"\t"+p.getEmision().getDia()+"/"+ p.getEmision().getMes()+"/"+ p.getEmision().getAño()+"\t"+p.getCaducidad().getDia()+"/"+ p.getCaducidad().getMes()+"/"+ p.getCaducidad().getAño());
    }
}

private void lista(DNI dni){ 
    imprime("Numero DNI\t\t: "+dni.getNumero()); 
    imprime("Nombres\t\t: "+dni.getDueño().getNombre()); 
    imprime("Apellidos\t\t: "+dni.getDueño().getApellido()); 
    imprime("Edad\t\t: "+dni.getDueño().getEdad()); 
    imprime("Peso\t\t: "+dni.getDueño().getPeso()); 
    imprime("Fecha Emision\t\t: "+dni.getEmision().getDia()+"/"+ dni.getEmision().getMes()+"/"+ dni.getEmision().getAño()); 
    imprime("Fecha Caducidad\t: "+dni.getCaducidad().getDia()+"/"+ dni.getCaducidad().getMes()+"/"+ dni.getCaducidad().getAño()); 
    imprime("--------------------------------------------------"); } 

private void imprime(String s){ txtSalida.append(s+"\n"); }

public void mensaje(String s){
    JOptionPane.showMessageDialog(this, s);//ctrl+barra espaciadora pa q busque JOptionPane
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cboMesCaducidad;
    private javax.swing.JComboBox cboMesEmision;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAñoCaducidad;
    private javax.swing.JTextField txtAñoEmision;
    private javax.swing.JTextField txtDiaCaducidad;
    private javax.swing.JTextField txtDiaEmision;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
