package p03e03;
import javax.swing.JOptionPane;

public class PanelPrincipal extends javax.swing.JPanel {
private ArregloDeCadenas ae;
  
    public PanelPrincipal() {
        initComponents();
        
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnReinicia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        txtTamaño = new javax.swing.JTextField();
        btnDimensiona = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Arreglo de Cadena"));
        txtNumero.setPreferredSize(new java.awt.Dimension(140, 60));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, java.awt.BorderLayout.LINE_START);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnReinicia.setText("Reinicia");
        btnReinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnReinicia);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        txtSalida.setPreferredSize(new java.awt.Dimension(164, 80));
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensiona el tamaño del arreglo"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));
        jPanel3.add(txtTamaño);

        btnDimensiona.setText("Dimensiona");
        btnDimensiona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDimensionaActionPerformed(evt);
            }
        });
        jPanel3.add(btnDimensiona);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNumeroActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
    String num = leeNumero();
    int p=ae.busca(num); 
    if(p!=-1)
    mensaje("Error: La cadena ingresada ya existe");
    else{ 
        ae.agrega(num); 
        mensaje("La cadena se ingreso correctamente");
        borra(); 
       }
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
// TODO add your handling code here:
    
     { lista(); }
    
}//GEN-LAST:event_btnListaActionPerformed

private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
 
    String num = leeNumero(); 
    int p=ae.busca(num); 
    if(p==-1) mensaje("Error: La cadena ingresada NO existe"); 
    else
        { ae.elimina(p); 
          lista(); 
        }
    
}//GEN-LAST:event_btnEliminaActionPerformed

private void btnReiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciaActionPerformed
  
    ae.setN(0); mensaje("El arreglo esta vacío.");
     txtSalida.setText("");
     txtNumero.setText("");
    
}//GEN-LAST:event_btnReiniciaActionPerformed

private void btnDimensionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDimensionaActionPerformed
// TODO add your handling code here:
    
    int dim = leeDimension();
    if(dim==Integer.MAX_VALUE)
        mensaje("Error: Ingrese un número entero");
    else{
    ae = new ArregloDeCadenas(dim);
    }
}//GEN-LAST:event_btnDimensionaActionPerformed

    public String leeNumero()
    { return txtNumero.getText(); } 
    
    public int leeDimension()
    { 
        try{
            return Integer.parseInt(txtTamaño.getText()); 
        }catch(Exception ex){
            return Integer.MAX_VALUE;
        }
    }
    public void mensaje(String s)
    { JOptionPane.showMessageDialog(this, s); } 
    
    public void lista()
    { 
     borra();
    for(int i=0; i<ae.getN(); i++)
    { imprime("a["+i+"]\t:"+ae.getNum(i)); } 
    }
    
    public void borra()
    { txtNumero.setText("");
      txtSalida.setText(""); 
      txtNumero.requestFocus(); } 
    
    public void imprime(String s)
    { txtSalida.append(s+"\n"); }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDimensiona;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReinicia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
