/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package P13E05;


import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class PanelCirculo extends javax.swing.JPanel {
Archivofiguras af=new Archivofiguras("FigurasP.txt");
    /**
     * Creates new form PanelCirculo
     */
    public PanelCirculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtradio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsalida = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Circulo"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtradio.setBorder(javax.swing.BorderFactory.createTitledBorder("Radio"));
        jPanel1.add(txtradio);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setText("Reporte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton3.setText("borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        txtsalida.setColumns(20);
        txtsalida.setRows(5);
        jScrollPane1.setViewportView(txtsalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txtsalida.setText("Figura\tRadio\tArea\tPrametro\n");
       for(int i=0;i<af.getN();i++){
           Figura f=af.getFigura(i);
           if(f instanceof Circulo)
               imprime(f.getNombre()+"\t"+
                       ((Circulo)(f)).getRadio()+"\t"+
                       f.area()+"\t"+
                       f.parametro());
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Figura a=new Circulo(leeradio());
       lista(a);
       af.agrega(a);
       af.graba();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     txtradio.setText("");
     txtsalida.setText("");
     txtradio.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  
        imprime("Area Mayor:\t"+af.AreaMayor());
       imprime("Area Menor:\t"+af.AreaMenor());
       imprime("Area Promedio:\t"+af.areaPromedio());
        imprime("parametro Mayor:\t"+af.parametroMayor());
       imprime("parametro Menor:\t"+af.parametroMenor());
       imprime("parametro Promedio:\t"+af.parametroPromedio());
   // af.grabareporte();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtradio;
    private javax.swing.JTextArea txtsalida;
    // End of variables declaration//GEN-END:variables
private double leeradio() {
       return Double.parseDouble(txtradio.getText());
    }
   

    private void lista(Figura f) {
        imprime(f.info());
    }

    private void imprime(String s) {
        txtsalida.append(s+"\n");
    }

    private void mensaje(String s) {
        JOptionPane.showMessageDialog(this, s);
    }
}
