/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package P13E05;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class PanelReporte extends javax.swing.JPanel {
    Archivofiguras af=new Archivofiguras("figurasP.txt");
    /**
     * Creates new form Archivo
     */
    public PanelReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtsalida = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte"));
        setLayout(new java.awt.BorderLayout());

        txtsalida.setColumns(20);
        txtsalida.setRows(5);
        txtsalida.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtsalidaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtsalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsalidaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtsalidaAncestorAdded
     try{
           FileReader f= new FileReader("Reporte.txt");
           BufferedReader br =new BufferedReader(f);
           String texto;
           while((texto=br.readLine())!=null){
               txtsalida.append(texto+"\n");

           }
       }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "Archivo no cargado");
       }
    }//GEN-LAST:event_txtsalidaAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtsalida;
    // End of variables declaration//GEN-END:variables

    private void imprime(String string) {
        txtsalida.append(string+"\n");
    }
}
