/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 19-feb-2013, 14:20:07
 */
package p02e04;

/**
 *
 * @author michael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /** Creates new form PanelPrincipal */
    public PanelPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtDiaEmision = new javax.swing.JTextField();
        cboMesEmision = new javax.swing.JComboBox();
        txtAñoEmision = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtDiaCaducidad = new javax.swing.JTextField();
        cboMesCaducidad = new javax.swing.JComboBox();
        txtAñoCaducidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de DNI"));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        txtNombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jPanel2.add(txtNombres);

        txtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));
        jPanel2.add(txtApellidos);

        txtEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));
        jPanel2.add(txtEdad);

        txtPeso.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        jPanel2.add(txtPeso);

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Emision"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        txtDiaEmision.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia"));
        jPanel5.add(txtDiaEmision);

        cboMesEmision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        cboMesEmision.setBorder(null);
        jPanel5.add(cboMesEmision);

        txtAñoEmision.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));
        jPanel5.add(txtAñoEmision);

        jPanel4.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Caducidad"));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        txtDiaCaducidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia"));
        jPanel6.add(txtDiaCaducidad);

        cboMesCaducidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cboMesCaducidad.setBorder(null);
        jPanel6.add(cboMesCaducidad);

        txtAñoCaducidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Año"));
        jPanel6.add(txtAñoCaducidad);

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel7.add(btnNuevo);

        btnBorrar.setText("Borrar");
        jPanel7.add(btnBorrar);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNumeroActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
   
 DNI nuevo = new DNI(leeNumero(),
             new Persona(leeNombres(), leeApellidos(), leeEdad(), leePeso()),
             new Fecha(leeDiaEmision(), leeMesEmision(), leeAñoEmision()), 
             new Fecha(leeDiaCaducidad(), leeMesCaducidad(), leeAñoCaducidad()) );
    
    nuevo.setNumero(leeNumero());
   // nuevo.setDueño(new Persona(leeNombres(), leeApellidos(), leeEdad(), leePeso())); solo con constructor
   lista(nuevo);
     
}//GEN-LAST:event_btnNuevoActionPerformed

private String leeNumero(){return txtNumero.getText();}
//guarda variables en la clase PERSONA
private String leeNombres(){return txtNombres.getText();}
private String leeApellidos(){return txtApellidos.getText();}
private int leeEdad(){return Integer.parseInt(txtEdad.getText());}
private double leePeso(){return Double.parseDouble(txtPeso.getText());}
private int leeDiaEmision(){ return Integer.parseInt(txtDiaEmision.getText());} 
private int leeMesEmision(){ return cboMesEmision.getSelectedIndex();} 
private int leeAñoEmision(){ return Integer.parseInt(txtAñoEmision.getText());} 
private int leeDiaCaducidad(){ return Integer.parseInt(txtDiaCaducidad.getText());}
//guarda variables en la clase FECHA

private int leeMesCaducidad(){ return cboMesCaducidad.getSelectedIndex();} 
private int leeAñoCaducidad(){ return Integer.parseInt(txtAñoCaducidad.getText());} 

private void lista(DNI dni){ 
    imprime("Numero DNI\t\t: "+dni.getNumero()); 
    imprime("Nombres\t\t: "+dni.getDueño().getNombre()); 
    imprime("Apellidos\t\t: "+dni.getDueño().getApellido()); 
    imprime("Edad\t\t: "+dni.getDueño().getEdad()); 
    imprime("Peso\t\t: "+dni.getDueño().getPeso()); 
    imprime("Fecha Emision\t\t: "+dni.getEmision().getDia()+"/"+ dni.getEmision().getMes()+"/"+ dni.getEmision().getAño()); 
    imprime("Fecha Caducidad\t: "+dni.getCaducidad().getDia()+"/"+ dni.getCaducidad().getMes()+"/"+ dni.getCaducidad().getAño()); 
    imprime("--------------------------------------------------"); } 

private void imprime(String s){ txtSalida.append(s+"\n"); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboMesCaducidad;
    private javax.swing.JComboBox cboMesEmision;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAñoCaducidad;
    private javax.swing.JTextField txtAñoEmision;
    private javax.swing.JTextField txtDiaCaducidad;
    private javax.swing.JTextField txtDiaEmision;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
