/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 18-feb-2013, 17:43:03
 */
package p01e03;

/**
 *
 * @author michael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /** Creates new form PanelPrincipal */
    public PanelPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSerie = new javax.swing.JTextField();
        cboMarca = new javax.swing.JComboBox();
        txtTamaño = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtSerie.setBorder(javax.swing.BorderFactory.createTitledBorder("Serie"));
        jPanel1.add(txtSerie);

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione marca", "Panasonic", "Samsumg", "LG" }));
        jPanel1.add(cboMarca);

        txtTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño de pulgadas"));
        jPanel1.add(txtTamaño);

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio US$"));
        jPanel1.add(txtPrecio);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
    TV nuevo = new TV();
    nuevo.setMarca(leeMarca());
    nuevo.setPrecio(leePrecio());
    nuevo.setSerie(leeSerie());
    nuevo.setTamaño(leeTamaño());
    
    lista(nuevo);
    
       
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
// TODO add your handling code here:
        txtSerie.setText("");
        txtPrecio.setText("");
        txtTamaño.setText("");
        cboMarca.setSelectedIndex(0);
        txtSalida.setText("");
    
    
    
}//GEN-LAST:event_btnBorrarActionPerformed

private String leeSerie(){return txtSerie.getText();}
private int leeTamaño(){return Integer.parseInt(txtTamaño.getText());}
private double leePrecio(){return Double.parseDouble(txtPrecio.getText());}
private int leeMarca(){return cboMarca.getSelectedIndex();}

private void lista(TV t)
{   imprime("Serie:\t"+t.getSerie());
    imprime("Tamaño:\t"+t.getTamaño());
    imprime("Marca:\t"+t.getMarca());
    imprime("Precio:\t"+t.getPrecio());
    
}

private void imprime(String s)
{   txtSalida.append(s+"\n");}






    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboMarca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
