/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelPrincipal.java
 *
 * Created on 18-feb-2013, 17:43:03
 */
package p05e03;
import javax.swing.JOptionPane;
/**
 *
 * @author michael
 */
       


public class PanelPrincipal extends javax.swing.JPanel {

    /** Creates new form PanelPrincipal */
    private ArregloTV atv;
    
    public PanelPrincipal() {
        initComponents();
        
        atv=new ArregloTV();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSerie = new javax.swing.JTextField();
        cboMarca = new javax.swing.JComboBox();
        txtTamaño = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtSerie.setBorder(javax.swing.BorderFactory.createTitledBorder("Serie"));
        jPanel1.add(txtSerie);

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione marca", "Panasonic", "Samsumg", "LG" }));
        jPanel1.add(cboMarca);

        txtTamaño.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño de pulgadas"));
        jPanel1.add(txtTamaño);

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio US$"));
        jPanel1.add(txtPrecio);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusca);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifica);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
    int p=atv.busca(leeSerie());
       if(p!=-1)
           mensaje("Error: DNI Repetido");
       else{
           TV nuevo=new TV(leeSerie(),leeMarca(),leeTamaño(),leePrecio());
           lista(nuevo);
           atv.agrega(nuevo);
       }
    
       
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
// TODO add your handling code here:
        txtSerie.setText("");
        txtPrecio.setText("");
        txtTamaño.setText("");
        cboMarca.setSelectedIndex(0);
        txtSalida.setText("");
    
    
    
}//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        
        int p=atv.busca(leeSerie());
       if(p==-1)
           mensaje("Error:Codigo no existe");
       else{
           TV pp=atv.getTV(p);
           lista(pp);
       }
        
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        
         int p=atv.busca(leeSerie());
       if(p==-1)
           mensaje("Error: DNI No encontrado");
       else{
           
           TV nuevo=new TV(leeSerie(),leeMarca(),leeTamaño(),leePrecio());
         
           atv.reemplaza(nuevo, p);
          
       }
        
        
        
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        
        listado();
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        
        
     imprime("Precio promedio\t:" +atv.PrecioPromedio());
     imprime("Precio mas alto\t:" +atv.MayorPrecio());
        
        
    }//GEN-LAST:event_btnReporteActionPerformed

private String leeSerie(){return txtSerie.getText();}
private int leeTamaño(){return Integer.parseInt(txtTamaño.getText());}
private double leePrecio(){return Double.parseDouble(txtPrecio.getText());}
private int leeMarca(){return cboMarca.getSelectedIndex();}

private void lista(TV t)
{   imprime("Serie:\t"+t.getSerie());
    imprime("Tamaño:\t"+t.getTamaño());
    imprime("Marca:\t"+t.getMarca());
    imprime("Precio:\t"+t.getPrecio());
    
}
public void listado(){
    txtSalida.setText("Serie\tMarca\tTamaño\tPrecio\n");
    for(int i=0;i<atv.getN();i++){
        TV p=atv.getTV(i);
        imprime(p.getSerie()+"\t"+p.getMarca()+"\t"+p.getTamaño()+"\t"+p.getPrecio());
    }
}


private void imprime(String s)
{   txtSalida.append(s+"\n");}


public void mensaje(String s){
    JOptionPane.showMessageDialog(this, s);//ctrl+barra espaciadora pa q busque JOptionPane
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cboMarca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
}
