/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p12e04;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablito
 */
public class JIBarcoDeGuerra extends javax.swing.JInternalFrame {
    
    ArchivoBarcoDeGuerra abg;

    /**
     * Creates new form JIBarcoMercante
     */
    public JIBarcoDeGuerra() {
        initComponents();
        abg = new ArchivoBarcoDeGuerra("guerras.txt");
        setSize(600,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtFlot = new javax.swing.JTextField();
        txtVel = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtArtilleria = new javax.swing.JTextField();
        txtAlcance = new javax.swing.JTextField();
        txtTripulacion = new javax.swing.JTextField();
        txtFoto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel4.add(txtNombre);

        txtFlot.setBorder(javax.swing.BorderFactory.createTitledBorder("Flotabilidad"));
        jPanel4.add(txtFlot);

        txtVel.setBorder(javax.swing.BorderFactory.createTitledBorder("Velocidad"));
        jPanel4.add(txtVel);

        jPanel2.add(jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        txtArtilleria.setBorder(javax.swing.BorderFactory.createTitledBorder("Artillería"));
        jPanel7.add(txtArtilleria);

        txtAlcance.setBorder(javax.swing.BorderFactory.createTitledBorder("Alcance"));
        jPanel7.add(txtAlcance);

        txtTripulacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Tripulación"));
        jPanel7.add(txtTripulacion);

        txtFoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        jPanel7.add(txtFoto);

        jPanel6.add(jPanel7);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnLista);

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel3.add(btnConsulta);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel3.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel3.add(btnElimina);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel3.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrar);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jPanel5.add(jScrollPane1);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        jPanel5.add(lblImagen);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        BarcoDeGuerra bg = abg.busca(leeNombre());
        if(bg != null){
            mensaje("Nombre repetido");
        }else{
            bg = new BarcoDeGuerra(leeNombre(), leeFlotabilidad(),
                leeVelocidad(), leeArtilleria(), leeFoto(), leeAlcance(),
                leeTripulacion());
            abg.agrega(bg);
            lista(bg);
            abg.graba();
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed

        if(abg.getN()==0){
            mensaje("Arreglo vacío!!");
        }else{
            lista();
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        BarcoDeGuerra bg = abg.busca(leeNombre());
        if(bg == null){
            mensaje("Nombre no encontrado");
        }else{
            txtSalida.setText("");
            lista(bg);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed

        int p = abg.busca1(leeNombre());
        if(p == -1){
            mensaje("Nombre no encontrado");
        }else{
            BarcoDeGuerra bg = new BarcoDeGuerra(leeNombre(), leeFlotabilidad(),
                leeVelocidad(), leeArtilleria(), leeFoto(), leeAlcance(),
                leeTripulacion());
            abg.modifica(bg, p);
            txtSalida.setText("");
            lista(bg);
            abg.graba();
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed

        BarcoDeGuerra bg = abg.busca(leeNombre());
        if(bg == null){
            mensaje("Nombre no encontrado");
        }else{
            abg.elimina(bg);
            txtSalida.setText("");
            lista();
            abg.graba();
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

        txtSalida.setText("");
        if(abg.getN()== 0){
            mensaje("Arreglo vacío!!");
        }else{
            lista();
            imprime("-----------------");
            imprime("Mayor Velocidad\t: "+abg.mayorVelocidad());
            imprime("Menor Velocidad\t: "+abg.menorVelocidad());
            imprime("Velocidad Promedio\t: "+abg.velocidadPromedio());
            imprime("-----------------");
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        txtNombre.setText("");
        txtFlot.setText("");
        txtVel.setText("");
        txtArtilleria.setText("");
        txtAlcance.setText("");
        txtTripulacion.setText("");
        txtFoto.setText("");
        txtSalida.setText("");
        lblImagen.setIcon(null);
        txtNombre.requestFocus();

    }//GEN-LAST:event_btnBorrarActionPerformed

    private String leeNombre(){return txtNombre.getText();}
    private String leeFlotabilidad(){return txtFlot.getText();}
    private double leeVelocidad(){return Double.parseDouble(txtVel.getText());}
    private String leeArtilleria(){return txtArtilleria.getText();}
    private String leeFoto(){return txtFoto.getText();}
    private double leeAlcance(){return Double.parseDouble(txtAlcance.getText());}
    private int leeTripulacion(){return Integer.parseInt(txtTripulacion.getText());}
        
    private void lista(){
        txtSalida.setText("");
        imprime("Nombre\tFlotabilidad\tVelocidad\tArtillería\tAlcance\t"
                + "Tripulación\tFoto");
        for(int i=0; i<abg.getN(); i++){
            BarcoDeGuerra bg = abg.getBarcoDeGuerra(i);
            imprime(bg.getNombre()+"\t"+bg.getFlotabilidad()+"\t"+
                    bg.getVelocidad()+"\t"+bg.getArtillería()+"\t"+
                    bg.getAlcance()+"\t"+bg.getTripulación()+"\t"+
                    bg.getFoto());
        }        
    }
   
    private void lista(BarcoDeGuerra g){
        imprime("Nombre\t:"+g.getNombre());
        imprime("Flotabilidad\t:"+g.getFlotabilidad());
        imprime("Velocidad\t:"+g.getVelocidad());
        imprime("Artillería\t:"+g.getArtillería());
        imprime("Alcance\t:"+g.getAlcance());
        imprime("Tripulación\t:"+g.getTripulación());
        imprime("Foto\t:"+g.getFoto());
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/fotos/"+
                g.getFoto()+".jpg")));        
    }       
    
    private void imprime(String s){txtSalida.append(s+"\n");}
    
    private void mensaje(String s){
        JOptionPane.showMessageDialog(this, s);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtAlcance;
    private javax.swing.JTextField txtArtilleria;
    private javax.swing.JTextField txtFlot;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtTripulacion;
    private javax.swing.JTextField txtVel;
    // End of variables declaration//GEN-END:variables
}
