/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p12e04;

/**
 *
 * @author Pablito
 */
public class Principal extends javax.swing.JFrame {
    
    JIBarcoMercante mercante = new JIBarcoMercante();
    JIBarcoDeGuerra guerra = new JIBarcoDeGuerra();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(615,565);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMercante = new javax.swing.JButton();
        btnGuerra = new javax.swing.JButton();
        desktopFondo = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MENÚ"));

        btnMercante.setText("Nuevo Barco Mercante");
        btnMercante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMercante);

        btnGuerra.setText("Nuevo Barco de Guerra");
        btnGuerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuerraActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuerra);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(desktopFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMercanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercanteActionPerformed
        
        if(guerra.isSelected()){
            guerra.dispose();
        }        
        desktopFondo.add(mercante);
        mercante.setVisible(true);
    }//GEN-LAST:event_btnMercanteActionPerformed

    private void btnGuerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuerraActionPerformed
        
        if(mercante.isSelected()){
            mercante.dispose();
        }        
        desktopFondo.add(guerra);
        guerra.setVisible(true);
    }//GEN-LAST:event_btnGuerraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuerra;
    private javax.swing.JButton btnMercante;
    private javax.swing.JDesktopPane desktopFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
