/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p13e02;

/**
 *
 * @author michael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCapitalInicial = new javax.swing.JTextField();
        txtTasaInteres = new javax.swing.JTextField();
        txtNumeroAños = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnInteresSimple = new javax.swing.JButton();
        btnInteresCompuesto = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de datos"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtCapitalInicial.setBorder(javax.swing.BorderFactory.createTitledBorder("Capital inicial"));
        jPanel1.add(txtCapitalInicial);

        txtTasaInteres.setBorder(javax.swing.BorderFactory.createTitledBorder("tasa interés"));
        jPanel1.add(txtTasaInteres);

        txtNumeroAños.setBorder(javax.swing.BorderFactory.createTitledBorder("numero años"));
        jPanel1.add(txtNumeroAños);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        btnInteresSimple.setText("Interes Simple");
        btnInteresSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresSimpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnInteresSimple);

        btnInteresCompuesto.setText("Interes Compuesto");
        btnInteresCompuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresCompuestoActionPerformed(evt);
            }
        });
        jPanel2.add(btnInteresCompuesto);

        btnBorrar.setText("Borrar");
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInteresSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresSimpleActionPerformed
        Interes a = new InteresSimple("Simple",leeCapitalInicial(),leeTasaInteres(),leeNumeroAños());
	lista(a);

    }//GEN-LAST:event_btnInteresSimpleActionPerformed

    private void btnInteresCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresCompuestoActionPerformed
        Interes b = new InteresCompuesto("Compuesto",leeCapitalInicial(),leeTasaInteres(),leeNumeroAños());
	lista(b);

    }//GEN-LAST:event_btnInteresCompuestoActionPerformed

    public int leeCapitalInicial(){return Integer.parseInt(txtCapitalInicial.getText());}
    public int leeNumeroAños(){return Integer.parseInt(txtNumeroAños.getText());}
    public double leeTasaInteres(){return Double.parseDouble(txtTasaInteres.getText());}
    
    
    public void lista(Interes t){
	imprime(t.info());
}
   
    public void imprime(String s)
    { txtSalida.setText(s+"\n");
       }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnInteresCompuesto;
    private javax.swing.JButton btnInteresSimple;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCapitalInicial;
    private javax.swing.JTextField txtNumeroAños;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtTasaInteres;
    // End of variables declaration//GEN-END:variables
}
