/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p13e01;

/**
 *
 * @author michael
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRadio = new javax.swing.JTextField();
        txtLado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnNuevoCirculo = new javax.swing.JButton();
        btnNuevoCuadrado = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de datos"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtRadio.setBorder(javax.swing.BorderFactory.createTitledBorder("Radio"));
        jPanel1.add(txtRadio);

        txtLado.setBorder(javax.swing.BorderFactory.createTitledBorder("Lado"));
        jPanel1.add(txtLado);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        btnNuevoCirculo.setText("Nuevo Circulo");
        btnNuevoCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCirculoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoCirculo);

        btnNuevoCuadrado.setText("Nuevo Cudrado");
        btnNuevoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCuadradoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoCuadrado);

        btnBorrar.setText("Borrar");
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCirculoActionPerformed
        Figura a = new Circulo(leeRadio());
	lista(a);

    }//GEN-LAST:event_btnNuevoCirculoActionPerformed

    private void btnNuevoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCuadradoActionPerformed
        Figura b = new Cuadrado(leeLado());
	lista(b);

    }//GEN-LAST:event_btnNuevoCuadradoActionPerformed

    public Double leeRadio(){return Double.parseDouble(txtRadio.getText());}
    public Double leeLado(){return Double.parseDouble(txtLado.getText());}
    
    public void lista(Figura f){
	imprime(f.info());
}
   
    public void imprime(String s)
    { txtSalida.setText(s+"\n");
       }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnNuevoCirculo;
    private javax.swing.JButton btnNuevoCuadrado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
