/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p12e05;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablito
 */
public class PanelPrincipal extends javax.swing.JPanel {
    protected ArchivoAutobus aa;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        aa = new ArchivoAutobus("autobuses.txt");
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoVehiculo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPotencia = new javax.swing.JTextField();
        txtFoto = new javax.swing.JTextField();
        txtPlazas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        txtMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Matrícula"));
        jPanel4.add(txtMatricula);

        txtModelo.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));
        jPanel4.add(txtModelo);

        txtPotencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Potencia"));
        jPanel4.add(txtPotencia);

        txtFoto.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        jPanel4.add(txtFoto);

        txtPlazas.setBorder(javax.swing.BorderFactory.createTitledBorder("N° Plazas"));
        jPanel4.add(txtPlazas);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsulta);

        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifica);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnReporte);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBorrar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jPanel3.add(jScrollPane1);

        lblImagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));
        jPanel3.add(lblImagen);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        AUTOBUS a = aa.busca(leeMatricula());
        if(a != null){
            mensaje("Matrícula repetida");
        }else{
            a = new AUTOBUS(leeMatricula(), leeModelo(), leeFoto(),
                    leePotencia(), leePlazas());
            aa.agrega(a);
            lista(a);
            aa.graba();
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        txtMatricula.setText("");
        txtModelo.setText("");
        txtPotencia.setText("");
        txtFoto.setText("");
        txtPlazas.setText("");
        txtSalida.setText("");
        lblImagen.setIcon(null);        
        txtMatricula.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed

        if(aa.getN()==0){
            mensaje("Arreglo vacío!!");
        }else{
            lista();
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed

        AUTOBUS a = aa.busca(leeMatricula());
        if(a == null){
            mensaje("MAtrícula no encontrada");
        }else{
            txtSalida.setText("");
            lista(a);
        }
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        
        int p = aa.busca1(leeMatricula());
        if(p == -1){
            mensaje("Matrícula no encontrada");
        }else{
            AUTOBUS a = new AUTOBUS(leeMatricula(), leeModelo(), leeFoto(),
                    leePotencia(), leePlazas());
            aa.modifica(a, p);
            txtSalida.setText("");
            lista(a);
            aa.graba();
        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed

        AUTOBUS a = aa.busca(leeMatricula());
        if(a == null){
            mensaje("Matrícula no encontrada");
        }else{
            aa.elimina(a);
            txtSalida.setText("");
            lista();
            aa.graba();
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

        txtSalida.setText("");
        if(aa.getN()== 0){
            mensaje("Arreglo vacío!!");
        }else{
            lista();
            imprime("-----------------");
            imprime("Mayor Potencia\t\t: "+aa.mayorPotencia());
            imprime("Menor Potencia\t\t: "+aa.menorPotencia());
            imprime("Potencia Promedio\t: "+aa.potenciaPromedio());
            imprime("-----------------");
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private String leeMatricula(){return txtMatricula.getText();}
    private String leeModelo(){return txtModelo.getText();}
    private String leeFoto(){return txtFoto.getText();}
    private Double leePotencia(){return Double.parseDouble(txtPotencia.getText());}    
    private int leePlazas(){return Integer.parseInt(txtPlazas.getText());}
    
    private void lista(){
        txtSalida.setText("");
        imprime("Matrícula\tModelo\tPotencia\tN° Plazas\tFoto");
        for(int i=0; i<aa.getN(); i++){
            AUTOBUS a = aa.getAutobus(i);
            imprime(a.getMatricula()+"\t"+a.getModelo()+"\t"+
                    a.getPotencia()+"\t"+a.getNumero_plazas()+"\t"+
                    a.getFoto());
        }        
    }
    
    private void lista(AUTOBUS a){
        imprime("Matrícula\t:"+a.getMatricula());
        imprime("Modelo\t:"+a.getModelo());
        imprime("Potencia\t:"+a.getPotencia());
        imprime("Plazas\t:"+a.getNumero_plazas());
        imprime("Foto\t:"+a.getFoto());
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/fotos/"+
                    a.getFoto()+".jpg")));
    }
    
    private void imprime(String s){txtSalida.append(s+"\n");}
    
    private void mensaje(String s){
        JOptionPane.showMessageDialog(this, s);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.ButtonGroup tipoVehiculo;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlazas;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
