package p03e01;
import javax.swing.JOptionPane;

public class PanelPrincipal extends javax.swing.JPanel {
private ArregloDeEnteros ae;
  
    public PanelPrincipal() {
        initComponents();
        
         ae = new ArregloDeEnteros();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnReinicia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero Entero"));
        txtNumero.setPreferredSize(new java.awt.Dimension(120, 60));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, java.awt.BorderLayout.LINE_START);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel2.add(btnLista);

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel2.add(btnReporte);

        btnReinicia.setText("Reinicia");
        btnReinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnReinicia);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        txtSalida.setPreferredSize(new java.awt.Dimension(164, 80));
        jScrollPane1.setViewportView(txtSalida);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNumeroActionPerformed

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
    int num = leeNumero();
    int p=ae.busca(num); 
    if(p!=-1)
    mensaje("Error: El número ingresado ya existe");
    else{ 
        ae.agrega(num); 
        mensaje("Numero ingresado correctamente");
//        lista(); 
       }
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
// TODO add your handling code here:
    
     { lista(); }
    
}//GEN-LAST:event_btnListaActionPerformed

private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
 
    int num = leeNumero(); 
    int p=ae.busca(num); 
    if(p==-1) mensaje("Error: El número ingresado NO existe"); 
    else
        { ae.elimina(p); 
          lista(); 
        }
    
}//GEN-LAST:event_btnEliminaActionPerformed

private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

    //lista(); 
    imprime("El menor valor es\t: "+ae.elMenor()); 
    imprime("El valor promedio es\t: "+ae.promedio()); 
    imprime("El mayor valor es\t: "+ae.elMayor());
    
}//GEN-LAST:event_btnReporteActionPerformed

private void btnReiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciaActionPerformed
  
    ae.setN(0); mensaje("El arreglo esta vacío.");
    txtSalida.setText("");
    
}//GEN-LAST:event_btnReiniciaActionPerformed

    public int leeNumero()
    { return Integer.parseInt(txtNumero.getText()); } 
    
    public void mensaje(String s)
    { JOptionPane.showMessageDialog(this, s); } 
    
    public void lista()
    { 
     borra();
    for(int i=0; i<ae.getN(); i++)
    { imprime("a["+i+"]\t:"+ae.getNum(i)); } 
    }
    
    public void borra()
    { txtNumero.setText("");
      txtSalida.setText(""); 
      txtNumero.requestFocus(); } 
    
    public void imprime(String s)
    { txtSalida.append(s+"\n"); }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReinicia;
    private javax.swing.JButton btnReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
